version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.3
    - 5.31.2
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.2.3
  - dependency-name: sweetalert2
    versions:
    - 10.14.0
    - 10.14.1
    - 10.15.0
    - 10.15.1
    - 10.15.2
    - 10.15.3
    - 10.15.4
    - 10.15.5
    - 10.15.6
    - 10.15.7
    - 10.16.0
    - 10.16.2
    - 10.16.5
    - 10.16.6
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.33
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
  - dependency-name: "@sweetalert2/themes"
    versions:
    - 4.0.2
    - 4.0.3
