pull_request_rules:
  - name: automatic merge on CI success and review - Dependabot
    conditions:
      - status-success=Basaingeal.Razor.SweetAlert2
      - status-success=DeepCode
      - author=dependabot-preview[bot]
      - base=develop
      - head~=dependabot\/npm_and_yarn\/develop\/(?!sweetalert2).*
    actions:
      merge:
        method: merge